# modules_part3.py: Modules 06, 07, README

modules_part3 = {}

# =============================================================================
# MODULE 06: Culture & Ownership (Managerial & HR)
# =============================================================================
modules_part3["06_Managerial_and_HR"] = {
    "title": "06: Culture, Ownership & Engineering Judgement",
    "prev_link": "05_System_Design_or_HIL.html",
    "prev_title": "05: LLD & Low-Latency System Design",
    "next_link": "07_Quick_Reference.html",
    "next_title": "07: Rapid Recall CheatSheet",
    "markdown": """# 06: Culture, Ownership & Engineering Judgement

Media.net carries the legendary **Directi engineering culture**: high autonomy, meritocracy, intense intellectual curiosity, and zero tolerance for superficial hand-waving.

---

## 1. Navigating the JD's AI Tools Directive

The Media.net Job Description contains a very specific clause:
> *"Use AI coding assistants and developer tools responsibly to accelerate development, debugging, testing and documentation—while independently validating the output and maintaining code quality.*
> *Ability to use AI tools as an engineering accelerator—not as a substitute for understanding, reasoning, testing or code ownership.*
> *Note: Interviews and the online assessment evaluate unassisted problem-solving. Your fluency with AI tools is assessed separately, through how you talk about the projects you've built with them."*

### How to Address This in Interviews
* **Never say**: *"AI wrote the code for me,"* or *"I just prompt Gemini/ChatGPT."*
* **Always frame AI as**:
  1. **A Fuzzing & Test-Case Generator**: *"I used LLM APIs to generate adversarial test inputs and verify edge cases in my parser."*
  2. **A Prototyping Accelerator**: *"I drafted the initial boilerplate using AI tools, but profiled every memory allocation, analyzed the generated bytecode, and refactored it for deterministic latency."*
  3. **Strict Code Ownership**: *"Every line of code deployed in my projects was understood, benchmarked, and owned by me. In production, hallucinations cost money and violate SLAs."*

---

## 2. High-Yield Behavioral Questions (STAR Method)

### Question 1: "Tell me about a time you faced a difficult technical bug under time pressure."
* **Situation**: While building the **Warehouse PathMapper** spatial routing engine, the algorithm crashed with segmentation faults and memory spikes on grids larger than $5,000 \\times 5,000$.
* **Task**: I had 48 hours before the client demonstration to scale the routing engine to $10,000 \\times 10,000$ grids within a 0.5-second execution budget on a standard laptop CPU.
* **Action**: I profiled the memory allocations using Valgrind and Python's `tracemalloc`. I discovered that dynamic allocation of millions of coordinate tuples was thrashing the garbage collector and causing cache invalidations. I refactored the search graph into flat, contiguous 1D array buffers and implemented a hierarchical topological waypoint graph, reducing node evaluations by 98%.
* **Result**: The engine scaled successfully to $10,000 \\times 10,000$ locations, executing in **under 0.48 seconds** with zero memory leaks.

---

### Question 2: "Tell me about a disagreement you had with a team member and how you resolved it."
* **Situation**: During the **Ziroh Labs Academic Alliance Program**, where I led a team of 5, two developers argued over whether to use an existing deep learning model (ResNet-50) or a lightweight custom unsupervised approach (HOG + Clustering) for video keyframe extraction.
* **Task**: As team lead, I had to ensure project completion ahead of schedule without sacrificing detection accuracy or causing friction.
* **Action**: Rather than deciding subjectively, I instituted an objective benchmark spike. I gave both engineers 24 hours to run their implementations against the same 10-video benchmark dataset, measuring inference speed (FPS), CPU memory usage, and keyframe extraction precision.
* **Result**: The data revealed that the unsupervised HOG approach ran **11 times faster** than ResNet with 96.45% comparable accuracy, making real-time processing viable. Both engineers agreed with the data-driven choice, and we delivered the project ahead of the client deadline.

---

### Question 3: "Why do you want to join Media.net?"
* **Key Points to Hit**:
  1. **Engineering at Massive Scale**: Media.net processes billions of programmatic ad requests across 500,000+ publisher sites. Solving problems where every millisecond counts directly excites me.
  2. **Pure Meritocracy & High Bar**: Media.net is famous for valuing genuine computer science depth over buzzwords.
  3. **Low-Latency Distributed Systems**: As an engineer with a dual background in CSE and Signal Processing, working on sub-50ms real-time auction engines aligns perfectly with my analytical and systems interests.
"""
}

# =============================================================================
# MODULE 07: Rapid Recall CheatSheet
# =============================================================================
modules_part3["07_Quick_Reference"] = {
    "title": "07: Rapid Recall CheatSheet",
    "prev_link": "06_Managerial_and_HR.html",
    "prev_title": "06: Culture & Ownership",
    "next_link": "README.html",
    "next_title": "3-Day Study Roadmap",
    "markdown": """# 07: Rapid Recall CheatSheet

A rapid-fire reference card for last-minute revision before Media.net online assessments and technical interviews.

---

## 1. C++ STL & Concurrency Rapid Reference

```cpp
// 1. Min-Heap for Top-K
std::priority_queue<int, std::vector<int>, std::greater<int>> min_heap;

// 2. Custom Comparator Priority Queue
auto cmp = [](const auto& a, const auto& b) { return a.price > b.price; };
std::priority_queue<Bid, std::vector<Bid>, decltype(cmp)> pq(cmp);

// 3. Binary Search
auto it = std::upper_bound(vec.begin(), vec.end(), target); // first elem > target
int idx = std::distance(vec.begin(), it);

// 4. Thread-Safe Mutex & RAII Lock
std::mutex mtx;
{
    std::lock_guard<std::mutex> lock(mtx); // auto releases on scope exit
}

// 5. Condition Variable
std::condition_variable cv;
std::unique_lock<std::mutex> ulock(mtx);
cv.wait(ulock, []{ return ready; }); // releases lock, sleeps, re-acquires
cv.notify_one();
```

---

## 2. Operating Systems & Network Rapid Formulas

* **Amdahl's Law (Speedup Limit)**:
  $$S_{\\text{latency}}(s) = \\frac{1}{(1 - p) + \\frac{p}{s}}$$
  *(Where $p$ is the parallel fraction and $s$ is the number of cores. If 10% is serial, speedup cannot exceed $10\\times$ even with infinite cores).*
* **Little's Law (Queueing Theory)**:
  $$L = \\lambda \\times W$$
  *(Average requests in system $L$ = Throughput $\\lambda$ $\\times$ Average response time $W$. For 50,000 req/sec at 50ms latency, system holds $50000 \\times 0.05 = 2,500$ in-flight requests).*
* **Bandwidth-Delay Product (BDP)**:
  $$\\text{BDP} = \\text{Bandwidth (bits/sec)} \\times \\text{RTT (sec)}$$
  *(Determines the optimal TCP socket receive buffer size to keep network pipe full).*

---

## 3. High-Yield SQL CheatSheet

```sql
-- 1. Nth Highest Salary using DENSE_RANK()
SELECT salary FROM (
    SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) as rk
    FROM employees
) t WHERE rk = 2 LIMIT 1;

-- 2. Rolling 7-Day Average Revenue
SELECT date, AVG(revenue) OVER (
    ORDER BY date 
    ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
) as rolling_7d_avg
FROM daily_revenue;

-- 3. Self-Join to find Employees earning more than their Manager
SELECT e.name AS employee
FROM employee e
JOIN employee m ON e.manager_id = m.id
WHERE e.salary > m.salary;
```

---

## 4. Ad-Tech & RTB Rapid Glossary

* **CPM (Cost Per Mille)**: Cost per 1,000 ad impressions (standard RTB pricing metric).
* **eCPM (Effective CPM)**: $\\frac{\\text{Total Earnings}}{\\text{Total Impressions}} \\times 1000$.
* **CTR (Click-Through Rate)**: $\\frac{\\text{Total Clicks}}{\\text{Total Impressions}} \\times 100\\%$.
* **Vickrey (Second-Price) Auction**: The highest bidder wins, but pays the price bid by the second-highest bidder (plus 1 cent). Ensures truthful bidding (dominant strategy).
* **Fill Rate**: $\\frac{\\text{Ads Rendered}}{\\text{Ad Requests Dispatched}} \\times 100\\%$.
* **Header Bidding**: Running client-side or server-side parallel auctions with multiple SSPs via Prebid.js before querying the primary ad server.

---

## 5. Adarsh Saurabh: Candidate Project Metrics

| Project | Core Stack | Key Authentic Metric to Quote |
| :--- | :--- | :--- |
| **Warehouse PathMapper** | Python, Heuristic Routing, Data Structures | $10,000 \\times 10,000$ grid computed in **$< 0.5$ seconds** on i5 CPU. |
| **Uplan** | Gemini 2.5 Pro, LangGraph, Python | **85% reduction** in manual verification; **98% token compression**. |
| **Alternative Data Radar** | Python, Next.js, SQL, Bright Data | Automated anti-bot proxy bypass; 0–100 pre-earnings corporate health score. |
"""
}

# =============================================================================
# MODULE: README (Study Roadmap)
# =============================================================================
modules_part3["README"] = {
    "title": "3-Day Study Roadmap • Media.net Preparation",
    "prev_link": "07_Quick_Reference.html",
    "prev_title": "07: Rapid Recall CheatSheet",
    "next_link": "index.html",
    "next_title": "Overview & Hub",
    "markdown": """# 3-Day Intensive Study Roadmap: Media.net SDE Intern

A focused, hour-by-hour preparation schedule designed to maximize conversion probability for Media.net's Online Assessment and Technical Interview rounds.

---

## Day 1: Algorithmic Rigor & Speedrun (OA Mastery)

### Morning (09:00 – 13:00): Core Dynamic Programming & Heaps
* **Module Review**: Study `01_Online_Test.html` (Problem 1: Top-K Vickrey Auction, Problem 4: Weighted Interval Scheduling).
* **Practice on LeetCode / InterviewBit**:
  * LeetCode 295: Find Median from Data Stream (Two Heaps pattern).
  * LeetCode 1235: Maximum Profit in Job Scheduling (Binary Search + DP).
  * LeetCode 300: Longest Increasing Subsequence ($O(N \\log N)$ patience sorting).

### Afternoon (14:00 – 18:00): Graphs & Advanced Traversal
* **Module Review**: Study `01_Online_Test.html` (Problem 5: DAG Critical Path & Cycle Detection).
* **Practice**:
  * Kahn's Algorithm for Topological Sort & Cycle Detection in Directed Graphs.
  * Dijkstra's Algorithm with `std::priority_queue` and path reconstruction.
  * Disjoint Set Union (DSU) with Path Compression and Union by Rank.

### Evening (19:00 – 22:30): Strings & Wildcard Tries
* **Module Review**: Study `01_Online_Test.html` (Problem 2: Wildcard Trie Contextual Matcher).
* **Timed Mock Assessment**: Solve 3 problems in 90 minutes on InterviewBit without IDE assistance.

---

## Day 2: Systems, Memory, OS, Networks & LLD

### Morning (09:00 – 13:00): Operating Systems Internals
* **Module Review**: Study `02_Technical_Rounds.html` (Section 1: Process vs Thread, Virtual Memory, Paging, Mutex vs Spinlock).
* **Hands-On**: Write a multithreaded Producer-Consumer queue in C++ using `std::mutex` and `std::condition_variable`.
* **Deep Review**: Deadlocks (4 Coffman conditions), page fault handling, TLB hit/miss latency.

### Afternoon (14:00 – 18:00): Computer Networks & DBMS Internals
* **Module Review**: Study `02_Technical_Rounds.html` (Section 2 & 3: TCP Keep-Alive, TIME_WAIT socket exhaustion, HTTP/2 multiplexing, B+ Tree indexing, ACID isolation levels).
* **SQL Query Drill**: Write queries for $N$-th highest salary (`DENSE_RANK()`), self-joins, and aggregations.

### Evening (19:00 – 22:30): Low-Level Design (Machine Coding)
* **Module Review**: Study `05_System_Design_or_HIL.html` (Section 1: Thread-Safe LRU Cache with TTL).
* **Code from Scratch**: Write, compile, and execute an LRU cache with expiration in clean, modular C++ without looking at reference code.

---

## Day 3: Ad-Tech Architecture & Resume Defense

### Morning (09:00 – 13:00): Ad-Tech Domain & Low-Latency HLD
* **Module Review**: Study `03_Domain_Deep_Dive.html` and `05_System_Design_or_HIL.html` (OpenRTB 2.5 spec, Sub-50ms SLA budget, Header Bidding vs Waterfall, Redis Bitmaps, HyperLogLog, Bloom filters).
* **System Design Practice**: Walk through the Real-Time Bidding Auction Coordinator architecture end-to-end.

### Afternoon (14:00 – 18:00): Candidate Resume Defense & Grilling Traps
* **Module Review**: Study `04_Candidate_Resume_Grilling.html`.
* **Verbal Rehearsal**:
  * Practice the 2-minute elevator pitch for **Warehouse PathMapper** (explain why topological abstraction beats raw grid search).
  * Practice the defense of **Uplan** against the Media.net AI clause (explain deterministic mathematical validation vs LLM non-determinism).
  * Practice defending your **M.Tech Signal Processing + B.Tech CSE** dual background.

### Evening (19:00 – 21:30): Rapid Recall & Behavioral Fit
* **Module Review**: Study `06_Managerial_and_HR.html` and `07_Quick_Reference.html`.
* **Mental Rehearsal**: Review the STAR stories for production bugs, technical disagreements, and leadership under pressure.
"""
}
